//ListDemoForLoop.iterateIntegerList();
        
    List<integer> listInteger = new List<integer>();
        listInteger.add(15); // index 0 
        listInteger.add(21); // index 1
        listInteger.add(10); // index 2
        listInteger.add(15); // index 3
        listInteger.add(15); // index 4
        integer sum = ListDemoForLoop.add(listInteger);
        system.debug('sum of list is '+sum);