public class Calculation {
    public integer add(integer a, integer b){
        integer sum = a + b;
        return sum;
    }
    public integer subtract(integer c, integer d){
        integer sum= c - d;
        return sum;
    }
    public integer multiply(integer e, integer f){
        integer sum = e * f;
        return sum;
    }
    public integer divide(integer g, integer h){
        integer sum = g/h;
        return sum;
    }
}
