car Bugatti = new car();
Bugatti.carName = 'skuuuuuurt';
Bugatti.carColor = 'Black';
system.debug('bugatti instance-->'+ Bugatti);
//Bugatti.drive();
Bugatti.driveAtMaxSpeed();







//Car bm = new car();
//access variable using 
//bm.carColor = 'black';
//system.debug('car color='+ bm.carColor);
//bm.SwitchOn();
//system.debug('bm car color is '+ bm.carColor);
//system.debug('bm max speed is '+ bm.maxSpeedKmPerHour);
