List<account> listAcc = new list<account>();

        Account acc = new account();
        acc.name = 'acc bulk k';
        acc.phone = '987654321';
        listAcc.add(acc);

       /* Account acc1 = new account();
        acc1.name = 'acc bulk John';
        acc1.phone = '987654321';
        listAcc.add(acc1);

        Account acc2 = new account();
        acc2.name = 'acc bulk John';
        acc2.phone = '987654321';
        listAcc.add(acc2);         */

        insert listAcc;