public class Address {
    public void homeAddress() {
        string yourName = 'Kelsie';
        integer totalMembers = 4;
        integer houseNumber = 2100;
        string houseName=' single family home';
        string StreetName = 'Cora';
        string cityName = 'Nashville';
        string stateName= 'Tennessee';
        string stateIsoCode= 'Tn';
        string countryName= 'Unite States of America';
        string countryIsoCode = 'USA';
        string zipCode= '37601';
        boolean isCurrentAdd = true; 

system.debug(yourName);
system.debug(totalMembers);
system.debug(houseNumber);
system.debug(houseName);
system.debug(StreetName);
system.debug(cityName);
system.debug(stateName);
system.debug(stateIsoCode);
system.debug(countryName);
system.debug(countryIsoCode);
system.debug(zipCode);
system.debug(isCurrentAdd);
    }
}
