public class Players{

    public void playing() {
        string player1Name= 'Allen';
        string player2Name= 'John';
        string player3Name= 'Tim';
        string player4Name= 'Jim';
        string player5Name= 'Alex';
        system.debug( player1Name);
        system.debug( player2Name);
        system.debug( player3Name);
        system.debug( player4Name);
        system.debug( player5Name);
    }
}